title: Kludge & Wheel
email: # TBD
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Author settings
author: Konstantin Smirnov
author-pic: avatar.png
about-author: Senior software engineer at Grid Dynamics Intl Inc, San Francisco, CA.

# Contact links
email: konstantin.statics@gmail.com
phone: # Add your Phone number
website: ksmirnov.github.io
linkedin: konstantin-statics
github: ksmirnov
facebook: staticsone

# Newsletter
mailchimp: # Add your MailChimp form identifier.

# Disqus
discus_identifier: ksmirnov-github-io # Add your discus identifier

# Tracker
analytics: # Google Analytics

# Paginate
paginate: 6
paginate_path: /page:num/

# Build settings
markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
